[package]
name = "coelho"
version = "0.1.0"
authors = ["Jacek Olczyk <jacek.olczyk98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.9.1"
clap = "2"
atty = "0.2"
chrono = "0.4"
